### ISSUE TITLE
Icont agent

### ISSUE THREAD

**Issue by Gianfranco97** [flyve-mdm/flyve-mdm-press-kit#11]
I need the following edited icon: https://github.com/flyve-mdm/flyve-mdm-press-kit/blob/develop/logotype/mdm-agent.svg

- Must be in the same format (svg)

- Should be like this:

![captura de pantalla 2017-08-16 a la s 3 54 54 p m](https://user-images.githubusercontent.com/19965590/29382658-49251ac0-829b-11e7-8d01-e5b2169b5c3a.png)

**Comment by Gianfranco97** [comment]
Greetings @mmillevoye 

I was wondering, when will this issue be ready?
Icon is needed for functionality

**Comment by mmillevoye** [comment]
Hi Gianfranco 

Here is the icon (github doesn't seems to support svg files) 
When you have due dates make it appears on issues so I can manage my time :) 

Have a nice day ! 

----- Mail original -----

De: "Gianfranco Gesu Manganiello Tiso" <notifications@github.com> 
À: "flyve-mdm/flyve-mdm-press-kit" <flyve-mdm-press-kit@noreply.github.com> 
Cc: "mmillevoye" <marie@teclib.com>, "Mention" <mention@noreply.github.com> 
Envoyé: Lundi 28 Août 2017 23:03:54 
Objet: Re: [flyve-mdm/flyve-mdm-press-kit] Icont agent (#11) 



Greetings @mmillevoye 

I was wondering, when will this issue be ready? 
Icon is needed for functionality 

— 
You are receiving this because you were mentioned. 
Reply to this email directly, view it on GitHub , or mute the thread . 




-- 


Marie Millevoye 
Graphiste / Webdesigner 
mmillevoye@teclib.com 



Tel. +33 1 79 97 02 78 - Fax. +33 1 72 70 31 18 
Facebook | Twitter | www.buy-the-way.com 




11, rue de Cambrai - 75019 Paris 

__ 
Buy The Way, agence web du groupe Teclib
